apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: api-server:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"

---
# Need to confirm for generative model
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generative-model-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: generative-model
  template:
    metadata:
      labels:
        app: generative-model
    spec:
      containers:
        - name: generative-model
          image: generative-model:latest

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-deployment
spec:
  selector:
    app: postgres
  template:
    metadata:
      labels:
        app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-deployment
spec:
  selector:
    app: kafka
  template:
    metadata:
      labels:
        app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
